### ISSUE TITLE
Error while loading the middleman server

### ISSUE THREAD

**Issue by gnapse** [gutenye/example-ember-with-middleman#2]
I cloned the repo, ran `bundle install` successfully, then `bundle exec middleman`, and I get the following error:

```
== The Middleman is loading
/Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rb-fsevent-0.9.2/lib/rb-fsevent/fsevent.rb:40:in `select': Bad file descriptor (Errno::EBADF)
        from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/rb-fsevent-0.9.2/lib/rb-fsevent/fsevent.rb:40:in `run'
        from /Users/ernesto/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/listen-0.5.3/lib/listen/adapters/darwin.rb:31:in `block in start'
```

I'm using middleman 3.3.7. Any ideas what the problem is?

**Comment by gutenye** [comment]
Things have been changed a lot since Ember first release, Ember now has a
much more robust build system,  I have switched to ember-CLI, so I don't
use and  maintain thus project anymore.
